### PR TITLE
improve the binding resolution

### PR DESCRIPTION
**Pull request by jfromaniello**
This improve the resolution of the binding file and specially messing with this thing which I do not like:

https://github.com/TooTallNate/node-bindings/blob/master/bindings.js#L102-L134

### CODE REVIEW

**Comment by defunctzombie** [comment]
What is the problem this solves? How is binding resolution improved and why does the bindings module not do the right thing for us out of the box?

/cc @TooTallNate

**Comment by jfromaniello** [comment]
If you don't pass the module_root node bindings use a trick that overrides
Error.prepareStack for getting the file path and it works, unless you have
some other thing that prevents overriding this function.

**Comment by defunctzombie** [comment]
Is this still needed? I don't see issue reports from others saying that something is broken. I would like to understand what is actually broken for you and why this is the best fix before merging in a change like this which has the potential to break things.

**Comment by defunctzombie** [comment]
Closed for lack of activity. If incorrect closure please see previous comment and we can revisit.

**Pull request closed without merging**
