### PR TITLE
Bump nan and added nodejs 4

### PR DESCRIPTION
**Pull request by listepo**

### CODE REVIEW

**Comment by jonathanong** [comment]
:+1:

**Comment by defunctzombie** [comment]
Reason for nan bump?

Also, iojs stuff can be removed while we are at it.

**Comment by listepo** [comment]
I believe that it is always important bug fixes. I think to learn formal plans io.js term support.

**Comment by defunctzombie** [comment]
I don't understand. Is there a bug that needs fixing? There is no need to upgrade if nothing is broken for any of the current node versions.

**Pull request closed without merging**
