### PR TITLE
chore(deps): update nan@2.3.2

### PR DESCRIPTION
**Pull request by Zertz**

### CODE REVIEW

**Comment by Qard** [comment]
Yeah, the previous attempt at node 6 support ended up spitting out errors due to a last minute deprecation warning addition, which is what necessitated the new version of nan.

**Comment by defunctzombie** [comment]
Sigh. This is exactly why I wanted to wait to update nan.

**Comment by Zertz** [comment]
Is anything wrong in this PR?

**Comment by defunctzombie** [comment]
@Zertz nope, nothing wrong. Just referencing comments I made here https://github.com/ncb000gt/node.bcrypt.js/pull/410#issuecomment-209733066

**Comment by defunctzombie** [comment]
Additionaly, does this prevent builds or is this a "nice to have"?

**Comment by Qard** [comment]
nan 2.2.0 works fine with the version of V8 in node v6, but a deprecation warning was added to node at the last minute that prints out a bunch of combined JS and C++ stack traces if `Template::set` is used, which was the case in the nan setMethod and setPrototypeMethod calls before 2.3.0.

As it is now, it's functional, but very noisy at load time.

**Comment by defunctzombie** [comment]
@Qard is this reproducible with the bcrypt codebase? I installed v6 (on osx), built, and ran tests with `npm test` against master and saw no warnings.

**Comment by Qard** [comment]
Ah, looks like bcrypt doesn't actually use the impacted interfaces, so it doesn't have the deprecation warning issue.

**Comment by defunctzombie** [comment]
Closing because it seems there is no issue here.

**Comment by Zertz** [comment]
Would you merge the PR if it was just adding Node 6 to CI?

**Comment by defunctzombie** [comment]
Yep.

**Pull request closed without merging**
