### PR TITLE
Update redirects

### PR DESCRIPTION
**Pull request by frankenbot**
Created with https://github.com/dkhamsing/frankenstein

### CODE REVIEW

**Comment by defunctzombie** [comment]
@frankenbot would be nice if the commit message referenced that it only changes the readme `README: update redirects`

**Comment by dkhamsing** [comment]
Should it be the commit or the pull request title ?

**Comment by defunctzombie** [comment]
@dkhamsing commit is best IMO that way if user manually merges or whatnot the intended message stays with the commit. PR title is a github specific thing.

**Comment by dkhamsing** [comment]
Hmm ok

**Pull request merged**
