### PR TITLE
Update nan

### PR DESCRIPTION
**Pull request by Qard**
Node v6 is incoming, and nan 2.2.x is needed to support it.

### CODE REVIEW

**Comment by defunctzombie** [comment]
@Qard ping me when v6 is closer to landing cause sometimes nan gets updated at the final moments cause some other stuff breaks and I'd like to avoid updating it many times.

**Comment by Qard** [comment]
Will do. RC1 is out now though, and bcrypt *is* currently broken on it, just for reference. I believe the plan is for v6 proper to drop in the next week or two, assuming no delays. We're tracking V8 5.x a bit before release this time, so there *is* still some risk of breakage.

**Comment by mikefrey** [comment]
Node v6 will likely land on 4/26.

**Comment by defunctzombie** [comment]
What's the situation with v8 and possibility of having to update nan again?

**Comment by Qard** [comment]
There's no changes this time that nan couldn't cover, so it's just a version bump. Doesn't look like there's any major changes left in the pipe either, so I think it's safe to say current nan is what is going to work with v6.

**Pull request merged**
