### PR TITLE
update to nan v2 (adds support for iojs 3)

### PR DESCRIPTION
**Pull request by defunctzombie**
Nan v2 required more code changes but also adds support for iojs 3 and
hopefully provides a more stable API which will not have to change as
much going forward.

### CODE REVIEW

**Comment by defunctzombie** [comment]
Travis build is failing on iojs v3 but this seems to be unrelated to this repo and caused by errors from the v8 code. Maybe a stricter compiler or some other changes. It builds on my OSX machine so it could also be linux specific. If anyone has a linux machine locally, please give this PR a try on a few versions of node and iojs.

**Comment by ruimarinho** [comment]
Working fine here, iojs v3.0.0 on OSX (El Cap). Thank you!

**Comment by jbergstroem** [comment]
@defunctzombie iojs requires gcc 4.8.x or newer (v8 is c++11 only nowadays). People [in this issue](https://github.com/travis-ci/travis-ci/issues/1379) seems to have gone through the same pains.

Changes LGTM.

**Comment by defunctzombie** [comment]
Sigh. Why doesn't travis use the correct gcc when you specify iojs :(

Seems like we need to file a new ticket with them saying iojs-v3 support is incomplete because no native modules can build.

**Comment by jbergstroem** [comment]
@defunctzombie thinking it might rather be choice of distro than jenkins being conservative. Anyway, seems to be a few one-liners to getting 4.8.x running at travis in that issue.

**Comment by kkoopa** [comment]
While this compiles for now, you still want to change all uses of `v8::Value::ToXXX` and `v8::Value::XXXValue` to `Nan::To<XXX>` https://github.com/nodejs/nan/blob/master/doc/converters.md#api_nan_to, since the former will be removed from V8 in coming versions.

I would also recommend `Nan::Utf8String` as a drop-in replacement of `v8::String::Utf8Value`, which handles invalid UTF-8 in a consistent way.

**Comment by defunctzombie** [comment]
@kkoopa can you give an example from this codebase of Nan::To<XXX> use. The nan docs are not so clear to me how I would update the following:

```c++
const ssize_t rounds = info[0]->Int32Value();
```

My first stab at it was
```c++
const ssize_t rounds = Nan::To<ssize_t>(info[0]).FromJust();
```

but this doesn't build.

**Comment by kkoopa** [comment]
Only the listed conversions are available. While `int64_t` is the closest to `ssize_t`, the original used `int32_t`.

**Comment by defunctzombie** [comment]
ssize_t depends on architecture iirc

So what would be the API to do the above conversion. Examples/docs are
lacking and/or unclear to me how when I would use these and how to work
with maybe objects.

Do I need to consult v8 maybe object docs?

**Comment by kkoopa** [comment]
They won't say more than what's written at https://github.com/nodejs/nan/blob/master/doc/maybe_types.md#api_nan_maybe

Use `Nan::Maybe<>::FromJust` if you are certain that it is valid, otherwise, use `Nan::Maybe<>FromMaybe` with a suitable default value.

The above conversion is done as
`const ssize_t rounds = Nan::To<int32_t>(info[0]);`

**Comment by defunctzombie** [comment]
Thanks, I will give that a try.

**Pull request merged**
