### PR TITLE
Update nan to 1.8.0 to fix iojs 2.0.0 build

### LINKED ISSUE #298: Bcrypt fails to build on io.js 2.0.0
Bcrypt fails to build when using io.js 2.0.0 on Heroku. Here are the logs, some of them may be related to other libraries: 

```
remote: Building source:
remote: 
remote: -----> Node.js app detected
remote: 
remote: -----> Reading application state
remote:        package.json...
remote:        build directory...
remote:        cache directory...
remote:        environment variables...
remote: 
remote:        ACHIEVEMENT UNLOCKED: iojs :)
remote: 
remote:        Node engine:         stable (iojs)
remote:        Npm engine:          unspecified
remote:        Start mechanism:     Procfile
remote:        node_modules source: package.json
remote:        node_modules cached: true
remote: 
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_MODULES_CACHE=true
remote: 
remote: -----> Installing binaries
remote:        Resolving iojs version stable via semver.io...
remote:        Downloading and installing iojs 2.0.0...
remote:        Using default npm version: 2.9.0
remote: 
remote: -----> Building dependencies
remote:        Installing node modules
remote:        
remote:        > bcrypt@0.8.2 install /tmp/build_ec0307398c67a7231b6dfd32b2835fa1/node_modules/bcrypt
remote:        > node-gyp rebuild
remote:        
remote:        make: Entering directory `/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/node_modules/bcrypt/build'
remote:          CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
remote:          CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
remote:          CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
remote:        In file included from ../node_modules/nan/nan_new.h:190:0,
remote:                         from ../node_modules/nan/nan.h:80,
remote:                         from ../src/bcrypt_node.cc:1:
remote:        ../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBase<v8::Signature>::return_t NanIntern::Factory<v8::Signature>::New(NanIntern::Factory<v8::Signature>::FTH, int, NanIntern::Factory<v8::Signature>::FTH*)’:
remote:        ../node_modules/nan/nan_implementation_12_inl.h:181:76: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, NanIntern::Factory<v8::Signature>::FTH&, int&, NanIntern::Factory<v8::Signature>::FTH*&)’
remote:           return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
remote:                                                                                    ^
remote:        ../node_modules/nan/nan_implementation_12_inl.h:181:76: note: candidate is:
remote:        In file included from /app/.node-gyp/2.0.0/src/node.h:42:0,
remote:                         from ../node_modules/nan/nan.h:24,
remote:                         from ../src/bcrypt_node.cc:1:
remote:        /app/.node-gyp/2.0.0/deps/v8/include/v8.h:4188:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>)
remote:           static Local<Signature> New(
remote:                                   ^
remote:        /app/.node-gyp/2.0.0/deps/v8/include/v8.h:4188:27: note:   candidate expects 2 arguments, 4 provided
remote:        ../src/bcrypt_node.cc: In member function ‘virtual void {anonymous}::SaltAsyncWorker::HandleOKCallback()’:
remote:        ../src/bcrypt_node.cc:85:59: warning: ‘v8::Local<v8::Value> node::Encode(const void*, size_t, node::encoding)’ is deprecated (declared at /app/.node-gyp/2.0.0/src/node.h:278): Use Encode(isolate, ...) [-Wdeprecated-declarations]
remote:                 argv[1] = Encode(salt.c_str(), salt.size(), BINARY);
remote:                                                                   ^
remote:        In file included from ../src/bcrypt_node.cc:1:0:
remote:        ../src/bcrypt_node.cc: In function ‘void {anonymous}::GenerateSaltSync(const v8::FunctionCallbackInfo<v8::Value>&)’:
remote:        ../src/bcrypt_node.cc:139:53: warning: ‘v8::Local<v8::Value> node::Encode(const void*, size_t, node::encoding)’ is deprecated (declared at /app/.node-gyp/2.0.0/src/node.h:278): Use Encode(isolate, ...) [-Wdeprecated-declarations]
remote:             NanReturnValue(Encode(salt, strlen(salt), BINARY));
remote:                                                             ^
remote:        ../node_modules/nan/nan.h:306:65: note: in definition of macro ‘NanReturnValue’
remote:         # define NanReturnValue(value) return args.GetReturnValue().Set(value)
remote:                                                                         ^
remote:        ../src/bcrypt_node.cc: In member function ‘virtual void {anonymous}::EncryptAsyncWorker::HandleOKCallback()’:
remote:        ../src/bcrypt_node.cc:172:67: warning: ‘v8::Local<v8::Value> node::Encode(const void*, size_t, node::encoding)’ is deprecated (declared at /app/.node-gyp/2.0.0/src/node.h:278): Use Encode(isolate, ...) [-Wdeprecated-declarations]
remote:                     argv[1] = Encode(output.c_str(), output.size(), BINARY);
remote:                                                                           ^
remote:        In file included from ../src/bcrypt_node.cc:1:0:
remote:        ../src/bcrypt_node.cc: In function ‘void {anonymous}::EncryptSync(const v8::FunctionCallbackInfo<v8::Value>&)’:
remote:        ../src/bcrypt_node.cc:223:61: warning: ‘v8::Local<v8::Value> node::Encode(const void*, size_t, node::encoding)’ is deprecated (declared at /app/.node-gyp/2.0.0/src/node.h:278): Use Encode(isolate, ...) [-Wdeprecated-declarations]
remote:             NanReturnValue(Encode(bcrypted, strlen(bcrypted), BINARY));
remote:                                                                     ^
remote:        ../node_modules/nan/nan.h:306:65: note: in definition of macro ‘NanReturnValue’
remote:         # define NanReturnValue(value) return args.GetReturnValue().Set(value)
remote:                                                                         ^
remote:        make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
remote:        make: Leaving directory `/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/node_modules/bcrypt/build'
remote:        gyp ERR! build error 
remote:        gyp ERR! stack Error: `make` failed with exit code: 2
remote:        gyp ERR! stack     at ChildProcess.onExit (/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
remote:        gyp ERR! stack     at emitTwo (events.js:87:13)
remote:        gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
remote:        gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
remote:        gyp ERR! System Linux 3.13.0-49-generic
remote:        gyp ERR! command "/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/.heroku/node/bin/iojs" "/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
remote:        gyp ERR! cwd /tmp/build_ec0307398c67a7231b6dfd32b2835fa1/node_modules/bcrypt
remote:        gyp ERR! node -v v2.0.0
remote:        gyp ERR! node-gyp -v v1.0.3
remote:        gyp ERR! not ok 
remote:        npm WARN installMany nopt was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
remote:        npm WARN installMany npmlog was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
remote:        npm WARN installMany request was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
remote:        npm WARN installMany semver was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
remote:        npm WARN installMany tar was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
remote:        npm WARN installMany tar-pack was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
remote:        npm WARN installMany mkdirp was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
remote:        npm WARN installMany rc was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
remote:        npm WARN installMany rimraf was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
remote:        
remote:        > kerberos@0.0.10 install /tmp/build_ec0307398c67a7231b6dfd32b2835fa1/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
remote:        > (node-gyp rebuild 2> builderror.log) || (exit 0)
remote:        
remote:        make: Entering directory `/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
remote:          CXX(target) Release/obj.target/kerberos/lib/kerberos.o
remote:        make: Leaving directory `/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
remote:        
remote:        > bson-ext@0.1.3 install /tmp/build_ec0307398c67a7231b6dfd32b2835fa1/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext
remote:        > node-pre-gyp install --fallback-to-build
remote:        
remote:        make: Entering directory `/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build'
remote:          CXX(target) Release/obj.target/bson/ext/bson.o
remote:        In file included from ../node_modules/nan/nan_new.h:190:0,
remote:                         from ../node_modules/nan/nan.h:80,
remote:                         from ../ext/bson.h:17,
remote:                         from ../ext/bson.cc:36:
remote:        ../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBase<v8::Signature>::return_t NanIntern::Factory<v8::Signature>::New(NanIntern::Factory<v8::Signature>::FTH, int, NanIntern::Factory<v8::Signature>::FTH*)’:
remote:        ../node_modules/nan/nan_implementation_12_inl.h:181:76: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, NanIntern::Factory<v8::Signature>::FTH&, int&, NanIntern::Factory<v8::Signature>::FTH*&)’
remote:           return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
remote:                                                                                    ^
remote:        ../node_modules/nan/nan_implementation_12_inl.h:181:76: note: candidate is:
remote:        In file included from ../ext/bson.cc:14:0:
remote:        /app/.node-gyp/2.0.0/deps/v8/include/v8.h:4188:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>)
remote:           static Local<Signature> New(
remote:                                   ^
remote:        /app/.node-gyp/2.0.0/deps/v8/include/v8.h:4188:27: note:   candidate expects 2 arguments, 4 provided
remote:        ../ext/bson.cc: In static member function ‘static void BSON::BSONDeserialize(const v8::FunctionCallbackInfo<v8::Value>&)’:
remote:        ../ext/bson.cc:825:44: warning: ‘ssize_t node::DecodeBytes(v8::Handle<v8::Value>, node::encoding)’ is deprecated (declared at /app/.node-gyp/2.0.0/src/node.h:297): Use DecodeBytes(isolate, ...) [-Wdeprecated-declarations]
remote:           ssize_t len = DecodeBytes(args[0], BINARY);
remote:                                                    ^
remote:        ../ext/bson.cc:833:41: warning: ‘ssize_t node::DecodeWrite(char*, size_t, v8::Handle<v8::Value>, node::encoding)’ is deprecated (declared at /app/.node-gyp/2.0.0/src/node.h:310): Use DecodeWrite(isolate, ...) [-Wdeprecated-declarations]
remote:           DecodeWrite(data, len, args[0], BINARY);
remote:                                                 ^
remote:        ../ext/bson.cc: In static member function ‘static void BSON::BSONSerialize(const v8::FunctionCallbackInfo<v8::Value>&)’:
remote:        ../ext/bson.cc:928:73: warning: ‘v8::Local<v8::Value> node::Encode(const void*, size_t, node::encoding)’ is deprecated (declared at /app/.node-gyp/2.0.0/src/node.h:278): Use Encode(isolate, ...) [-Wdeprecated-declarations]
remote:           Local<Value> bin_value = Encode(serialized_object, object_size, BINARY)->ToString();
remote:                                                                                 ^
remote:        make: *** [Release/obj.target/bson/ext/bson.o] Error 1
remote:        make: Leaving directory `/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build'
remote:        gyp ERR! build error 
remote:        gyp ERR! stack Error: `make` failed with exit code: 2
remote:        gyp ERR! stack     at ChildProcess.onExit (/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
remote:        gyp ERR! stack     at emitTwo (events.js:87:13)
remote:        gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
remote:        gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
remote:        gyp ERR! System Linux 3.13.0-49-generic
remote:        gyp ERR! command "/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/.heroku/node/bin/iojs" "/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release/bson.node" "--module_name=bson" "--module_path=/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release"
remote:        gyp ERR! cwd /tmp/build_ec0307398c67a7231b6dfd32b2835fa1/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext
remote:        gyp ERR! node -v v2.0.0
remote:        gyp ERR! node-gyp -v v1.0.3
remote:        gyp ERR! not ok 
remote:        node-pre-gyp ERR! build error 
remote:        node-pre-gyp ERR! stack Error: Failed to execute '/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/.heroku/node/bin/iojs /tmp/build_ec0307398c67a7231b6dfd32b2835fa1/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release/bson.node --module_name=bson --module_path=/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release' (1)
remote:        node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
remote:        node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
remote:        node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
remote:        node-pre-gyp ERR! stack     at maybeClose (child_process.js:953:16)
remote:        node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1020:5)
remote:        node-pre-gyp ERR! System Linux 3.13.0-49-generic
remote:        node-pre-gyp ERR! command "/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/.heroku/node/bin/iojs" "/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
remote:        node-pre-gyp ERR! cwd /tmp/build_ec0307398c67a7231b6dfd32b2835fa1/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext
remote:        node-pre-gyp ERR! node -v v2.0.0
remote:        node-pre-gyp ERR! node-pre-gyp -v v0.6.4
remote:        node-pre-gyp ERR! not ok 
remote:        Failed to execute '/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/.heroku/node/bin/iojs /tmp/build_ec0307398c67a7231b6dfd32b2835fa1/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release/bson.node --module_name=bson --module_path=/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release' (1)
remote:        npm WARN optional dep failed, continuing bson-ext@0.1.3
remote:        
remote:        > bson@0.3.1 install /tmp/build_ec0307398c67a7231b6dfd32b2835fa1/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson
remote:        > (node-gyp rebuild 2> builderror.log) || (exit 0)
remote:        
remote:        npm ERR! Linux 3.13.0-49-generic
remote:        npm ERR! argv "/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/.heroku/node/bin/iojs" "/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/.heroku/node/bin/npm" "install" "--unsafe-perm" "--quiet" "--userconfig" "/tmp/build_ec0307398c67a7231b6dfd32b2835fa1/.npmrc"
remote:        npm ERR! node v2.0.0
remote:        npm ERR! npm  v2.9.0
remote:        npm ERR! code ELIFECYCLE
remote:        
remote:        npm ERR! bcrypt@0.8.2 install: `node-gyp rebuild`
remote:        npm ERR! Exit status 1
remote:        npm ERR! 
remote:        npm ERR! Failed at the bcrypt@0.8.2 install script 'node-gyp rebuild'.
remote:        npm ERR! This is most likely a problem with the bcrypt package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     node-gyp rebuild
remote:        npm ERR! You can get their info via:
remote:        npm ERR!     npm owner ls bcrypt
remote:        npm ERR! There is likely additional logging output above.
remote:        
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_ec0307398c67a7231b6dfd32b2835fa1/npm-debug.log
remote: 
remote: -----> Build failed
remote: 
remote:        We're sorry this build is failing!
remote:        
remote:        Are you running into a common issue?
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:        
remote:        If you're stuck, please submit a ticket so we can help:
remote:        https://help.heroku.com/
remote:        
remote:        Love,
remote:        Heroku
remote: 
remote:  !     Push rejected, failed to compile Node.js app
```

### PR DESCRIPTION
**Pull request by topaxi**
There are some deprecation warnings in the build though...

Fixes #298

### CODE REVIEW

**Comment by nmccready** [comment]
bump

**Comment by MateusZitelli** [comment]
:+1:

**Comment by dhritzkiv** [comment]
:+1: as well.

Suggestion: add iojs targets under `node_js` to the `.travis.yml` file:

````yaml
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "iojs-v1.8.0"
  - "iojs-v2.0.0" 
````

So we can verify that it compiles and tests properly on iojs

**Comment by imyller** [comment]
Referencing iojs/io.js#1620

**Comment by gordalina** [comment]
Bump

**Comment by cesarandreu** [comment]
:+1:

**Comment by kkoopa** [comment]
You want 1.8.4, not 1.8.0.

**Comment by imyller** [comment]
Exactly, 1.8.4 not 1.8.0
My PR #300 for `~1.8` would have bumped to latest 1.8.4 (and then stayed with 1.8.x line), but node.bcrypt.js wants to use exact versions for some reason.

**Comment by gordalina** [comment]
:+1: for `1.8.4`

**Comment by topaxi** [comment]
Updated all dependencies to the newest versions

**Comment by alanpurple** [comment]
+1

**Comment by gordalina** [comment]
You could also add in `.travis.yml` `iojs-v1` and `iojs-v2`

**Comment by defunctzombie** [comment]
@kkoopa Do you think this is ready to go? no more nan updates that will need to be made immediately?

**Comment by kkoopa** [comment]
Well, according to current plans, io.js 3.0 with V8 4.3 should come out in a month or so. This will require NAN 2.0, which will have breaking changes to accommodate the Maybe monads introduced in V8 4.3. So you'll have to do some rewriting then, but there is no reason not to do this simple upgrade in the meantime.

**Comment by imyller** [comment]
Business as usual and an infinite loop :)

V8 evolves. NAN updates accordingly. Packages update NAN dependencies. And then we start all over again.

**Comment by nmccready** [comment]
Working thank you!

**Pull request merged**
