### PR TITLE
mod; support io.js

### PR DESCRIPTION
**Pull request by wavded**
nan 1.5.0 adds support for io.js allowing the bindings to build

### CODE REVIEW

**Comment by mgenev** [comment]
yay! this will enable me to use iojs in my app

**Comment by defunctzombie** [comment]
@ncb000gt do you want to merge this and drop support for 0.6?

**Comment by Fishrock123** [comment]
You guys still support 0.6? o.0

**Comment by coma** [comment]
:+1:

**Comment by corbinu** [comment]
+1

**Pull request merged**
